/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../my.module';
class MyModuleInjector extends import0.ɵNgModuleInjector<import1.MyModule> {
  _MyModule_0:import1.MyModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.MyModule {
    this._MyModule_0 = new import1.MyModule();
    return this._MyModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.MyModule)) { return this._MyModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MyModuleNgFactory:import0.NgModuleFactory<import1.MyModule> = new import0.NgModuleFactory<any>(MyModuleInjector,import1.MyModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvamVjdHMvbW9kdWxlMS9teS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRjovUHJvamVjdHMvbW9kdWxlMS9teS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
