/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../main.component';
const styles_MainComponent:any[] = ([] as any[]);
export const RenderType_MainComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MainComponent,
  data: {}
}
);
export function View_MainComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),['Module1 Component']))],(null as any),(null as any));
}
function View_MainComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'module1-component',([] as any[]),(null as any),(null as any),(null as any),View_MainComponent_0,RenderType_MainComponent)),
    import0.ɵdid(49152,(null as any),0,import1.MainComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MainComponentNgFactory:import0.ComponentFactory<import1.MainComponent> = import0.ɵccf('module1-component',import1.MainComponent,View_MainComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovUHJvamVjdHMvbW9kdWxlMS9tYWluLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9Qcm9qZWN0cy9tb2R1bGUxL21haW4uY29tcG9uZW50LnRzIiwibmc6Ly8vRjovUHJvamVjdHMvbW9kdWxlMS9tYWluLmNvbXBvbmVudC50cy5NYWluQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9GOi9Qcm9qZWN0cy9tb2R1bGUxL21haW4uY29tcG9uZW50LnRzLk1haW5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJNb2R1bGUxIENvbXBvbmVudCIsIjxtb2R1bGUxLWNvbXBvbmVudD48L21vZHVsZTEtY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkNBQTs7OztJQ0FBO2dCQUFBOzs7OyJ9
